version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "1992:1992"
    depends_on:
      - server
    restart: always

  server:
    build: ./server
    ports:
      - "3000:3000"

